In [15]:
import pandas as pd

In [16]:
df = pd.read_csv("../data/raw/Pattern Seekers Interview (Responses) - Form Responses 1.csv")

df.head(10)

,Timestamp,What is your name?,How many hours of sleep did you get yesterday?,Rate your roommate on a scale of 1-10,How good is the food?,How is the cow?,Which group is the best in Cluster 11?
0,7/8/2025 9:50:20,2,cake,5,2,like beef,Pattern Seekers
1,7/8/2025 9:50:21,2,8,10,4,I like the milk,Group 5
2,7/8/2025 9:50:29,2,7,10,3,good,Group 5
3,7/8/2025 9:50:31,2,1,8,3,moo,Group 5
4,7/8/2025 9:50:35,3,6,8,4,good,Group 5
5,7/8/2025 9:51:04,2,6 hours 9 minutes,10,1,Moo,Pattern Seekers
6,7/8/2025 9:51:08,3,54,8,3,moo,Pattern Seekers
7,7/8/2025 9:51:25,2,2,10,5,cheeseburger,Group 5
8,7/8/2025 9:51:25,2,8,10,3,it wants to eat you,Pattern Seekers
9,7/8/2025 9:51:32,3,9,10,3,smelly,Pattern Seekers

In [17]:
# Calculate the mean of realistic sleep values
mean_sleep = sleep_numeric[mask_realistic].mean()

# Impute missing/unrealistic values with the mean
df_sleep_to_impute_imputed = df_sleep_to_impute.copy()
df_sleep_to_impute_imputed["How many hours of sleep did you get yesterday?"] = mean_sleep

# Combine imputed and realistic data
df = pd.concat([df_realistic_sleep, df_sleep_to_impute_imputed], ignore_index=True)

df.head(12)

,Timestamp,What is your name?,How many hours of sleep did you get yesterday?,Rate your roommate on a scale of 1-10,How good is the food?,How is the cow?,Which group is the best in Cluster 11?
0,7/8/2025 9:50:21,2,8,10,4,I like the milk,Group 5
1,7/8/2025 9:50:29,2,7,10,3,good,Group 5
2,7/8/2025 9:50:31,2,1,8,3,moo,Group 5
3,7/8/2025 9:50:35,3,6,8,4,good,Group 5
4,7/8/2025 9:51:25,2,2,10,5,cheeseburger,Group 5
5,7/8/2025 9:51:25,2,8,10,3,it wants to eat you,Pattern Seekers
6,7/8/2025 9:51:32,3,9,10,3,smelly,Pattern Seekers
7,7/8/2025 9:53:40,2,6.51,8,4,the cow is udderly my gramma,Pattern Seekers
8,7/8/2025 9:54:01,1,1,1,1,1,Pattern Seekers
9,7/8/2025 9:50:20,2,5.39,5,2,like beef,Pattern Seekers
10,7/8/2025 9:51:04,2,5.39,10,1,Moo,Pattern Seekers
11,7/8/2025 9:52:03,2,5.39,10,1,mooooooo,Pattern Seekers

In [18]:
!pip install vaderSentiment
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

Requirement already satisfied: vaderSentiment in /opt/miniconda3/envs/cosmos/lib/python3.12/site-packages (3.3.2)
Requirement already satisfied: requests in /opt/miniconda3/envs/cosmos/lib/python3.12/site-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/miniconda3/envs/cosmos/lib/python3.12/site-packages (from requests->vaderSentiment) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/miniconda3/envs/cosmos/lib/python3.12/site-packages (from requests->vaderSentiment) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/miniconda3/envs/cosmos/lib/python3.12/site-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/miniconda3/envs/cosmos/lib/python3.12/site-packages (from requests->vaderSentiment) (2025.6.15)

In [19]:
analyzer = SentimentIntensityAnalyzer()

# Apply sentiment analysis to the "How is the cow?" column
df['cow_sentiment'] = df['How is the cow?'].astype(str).apply(lambda x: analyzer.polarity_scores(x)['compound'])

# Show the sentiment scores
df[['How is the cow?', 'cow_sentiment']]

df['How is the cow?'] = df['How is the cow?']

df.head()

,Timestamp,What is your name?,How many hours of sleep did you get yesterday?,Rate your roommate on a scale of 1-10,How good is the food?,How is the cow?,Which group is the best in Cluster 11?,cow_sentiment
0,7/8/2025 9:50:21,2,8,10,4,I like the milk,Group 5,0.3612
1,7/8/2025 9:50:29,2,7,10,3,good,Group 5,0.4404
2,7/8/2025 9:50:31,2,1,8,3,moo,Group 5,0.0000
3,7/8/2025 9:50:35,3,6,8,4,good,Group 5,0.4404
4,7/8/2025 9:51:25,2,2,10,5,cheeseburger,Group 5,0.0000

In [ ]:
df.columns = ["timestamp", "name", "sleep_hours", "roommate_rating", "food_quality", "how_is_the_cow", "best_cluster", "cow_sentiment"]

df = df.drop("timestamp", axis=1)

ValueError: Length mismatch: Expected axis has 7 elements, new values have 8 elements

In [26]:

df.head(16)

,name,sleep_hours,roommate_rating,food_quality,how_is_the_cow,best_cluster,cow_sentiment
0,2,8,10,4,I like the milk,Group 5,0.3612
1,2,7,10,3,good,Group 5,0.4404
2,2,1,8,3,moo,Group 5,0.0000
3,3,6,8,4,good,Group 5,0.4404
4,2,2,10,5,cheeseburger,Group 5,0.0000
5,2,8,10,3,it wants to eat you,Pattern Seekers,0.0000
6,3,9,10,3,smelly,Pattern Seekers,0.0000
7,2,6.51,8,4,the cow is udderly my gramma,Pattern Seekers,0.0000
8,1,1,1,1,1,Pattern Seekers,0.0000
9,2,5.39,5,2,like beef,Pattern Seekers,0.3612
10,2,5.39,10,1,Moo,Pattern Seekers,0.0000
11,2,5.39,10,1,mooooooo,Pattern Seekers,0.0000
12,3,5.39,7,1,good,Pattern Seekers,0.4404
13,3,5.39,8,3,moo,Pattern Seekers,0.0000
14,2,5.39,6,1,well,Pattern Seekers,0.2732
15,1,5.39,10,3,fine,Group 5,0.2023